Upgrade to v1.136.0 of the AliCloud Terraform Provider
pulumi/pulumi-alicloud pull request #204
Opened 2021-09-21 16:42 UTC by stack72

Fixes: #200
Fixes: #201
Fixes: #203﻿

2021-09-27 12:23 UTC, mikhailshilkov reviewed
A few suggestions

2021-09-27 12:23 UTC, mikhailshilkov commented on provider/resources.go
> +	databseFilesystemMod   = "DatabaseFilesystem"
```suggestion
	databaseFilesystemMod   = "DatabaseFilesystem"
```

2021-09-27 12:23 UTC, mikhailshilkov commented on provider/resources.go
> +			"alicloud_cms_metric_rule_template":    {Tok: resource(cmsMod, "MetricRuleTemlate")},
```suggestion
			"alicloud_cms_metric_rule_template":    {Tok: resource(cmsMod, "MetricRuleTemplate")},
```

2021-09-27 12:23 UTC, mikhailshilkov commented on provider/resources.go
> +			"alicloud_cms_metric_rule_templates":     {Tok: dataSource(cmsMod, "getRuleTemplates")},
```suggestion
			"alicloud_cms_metric_rule_templates":     {Tok: dataSource(cmsMod, "getMetricRuleTemplates")},
```

2021-10-01 18:35 UTC, lblackstone requested changes

2021-10-01 18:35 UTC, lblackstone commented on provider/resources.go
> +			"alicloud_msc_sub_contacts":      {Tok: dataSource(alicloudMod, "getMscSubContracts")},
```suggestion
			"alicloud_msc_sub_contacts":      {Tok: dataSource(alicloudMod, "getMscSubContacts")},
```

2021-10-01 18:35 UTC, lblackstone commented on provider/resources.go
> +			"alicloud_video_surveillance_system_groups": {Tok: dataSource(vsMod, "getSystemGroups")},
Should this be `alicloud_vs_system_groups`?

2021-10-04 11:28 UTC, stack72 commented on provider/resources.go
> +			"alicloud_video_surveillance_system_groups": {Tok: dataSource(vsMod, "getSystemGroups")},
Nah, they broke their naming convention :D So _vs_ is still _video_surveillance_ :/

2021-10-04 11:37 UTC, stack72 commented on provider/resources.go
> +			"alicloud_msc_sub_contacts":      {Tok: dataSource(alicloudMod, "getMscSubContracts")},
Great catch! thanks

2021-10-04 15:15 UTC, lblackstone approved these changes

2021-10-04 15:19 UTC, merged